// <auto-generated />
using System;
using BarrelsAccounting.Accounting.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accounting.Migrations
{
    [DbContext(typeof(SearchDbContext))]
    partial class SearchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarrelsAccounting.Accounting.Dal.ReadOnlyModel.BarrelModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Batch");

                    b.Property<double>("BruttoWeight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("double precision")
                        .HasColumnName("BruttoWeight");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTime");

                    b.Property<DateTime?>("DeletedDateTime")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedDateTime");

                    b.Property<bool>("IsDrained")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("boolean")
                        .HasColumnName("IsDrained");

                    b.Property<double>("NettoWeight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("double precision")
                        .HasColumnName("NettoWeight");

                    b.Property<string>("Number")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Number");

                    b.Property<DateOnly>("ProductionDate")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("date")
                        .HasColumnName("ProductionDate");

                    b.Property<string>("Ral")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Ral");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<Guid?>("StorageObjectId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("StorageObjectId");

                    b.HasKey("Id");

                    b.ToTable("Barrel", (string)null);
                });

            modelBuilder.Entity("BarrelsAccounting.Accounting.Dal.ReadOnlyModel.RalModel", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.HasKey("Code");

                    b.HasIndex("Code");

                    b.ToTable("Ral", (string)null);
                });

            modelBuilder.Entity("BarrelsAccounting.Accounting.Domain.Barrel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Batch");

                    b.Property<double>("BruttoWeight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("double precision")
                        .HasColumnName("BruttoWeight");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateTime");

                    b.Property<DateTime?>("DeletedDateTime")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedDateTime");

                    b.Property<bool>("IsDrained")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("boolean")
                        .HasColumnName("IsDrained");

                    b.Property<double>("NettoWeight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("double precision")
                        .HasColumnName("NettoWeight");

                    b.Property<string>("Number")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Number");

                    b.Property<DateOnly>("ProductionDate")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("date")
                        .HasColumnName("ProductionDate");

                    b.Property<string>("Ral")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Ral");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<Guid?>("StorageObjectId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("StorageObjectId");

                    b.HasKey("Id");

                    b.HasIndex("Batch");

                    b.HasIndex("Code");

                    b.HasIndex("Id");

                    b.HasIndex("Number");

                    b.HasIndex("Status");

                    b.HasIndex("StorageObjectId");

                    b.ToTable("Barrel", (string)null);
                });

            modelBuilder.Entity("BarrelsAccounting.Accounting.Domain.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("BarrelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BarrelId");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<string>("OperationPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OperationPayload");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OperationType");

                    b.Property<Guid?>("StorageObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("StorageObjectId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("DateTime");

                    b.HasIndex("Id");

                    b.HasIndex("OperationType");

                    b.HasIndex("StorageObjectId");

                    b.ToTable("Journal", (string)null);
                });

            modelBuilder.Entity("BarrelsAccounting.Accounting.Domain.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Code");

                    b.Property<Guid?>("DefaultStoragePlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("DefaultStoragePlaceId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("StorageTypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Storage", (string)null);

                    b.HasDiscriminator<string>("StorageTypeDiscriminator").HasValue("Storage");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BarrelsAccounting.Accounting.Domain.StorageObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Barcode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uuid")
                        .HasColumnName("StorageId");

                    b.Property<string>("StorageObjectTypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("StorageObject", (string)null);

                    b.HasDiscriminator<string>("StorageObjectTypeDiscriminator").HasValue("StorageObject");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BarrelsAccounting.Accounting.Domain.AcceptanceStorage", b =>
                {
                    b.HasBaseType("BarrelsAccounting.Accounting.Domain.Storage");

                    b.HasDiscriminator().HasValue("Acceptance");
                });

            modelBuilder.Entity("BarrelsAccounting.Accounting.Domain.ProductionStorage", b =>
                {
                    b.HasBaseType("BarrelsAccounting.Accounting.Domain.Storage");

                    b.HasDiscriminator().HasValue("Production");
                });

            modelBuilder.Entity("BarrelsAccounting.Accounting.Domain.Aggregate", b =>
                {
                    b.HasBaseType("BarrelsAccounting.Accounting.Domain.StorageObject");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("Volume");

                    b.HasIndex("StorageId");

                    b.HasDiscriminator().HasValue("Aggregate");
                });

            modelBuilder.Entity("BarrelsAccounting.Accounting.Domain.StoragePlace", b =>
                {
                    b.HasBaseType("BarrelsAccounting.Accounting.Domain.StorageObject");

                    b.HasDiscriminator().HasValue("StoragePlace");
                });

            modelBuilder.Entity("BarrelsAccounting.Accounting.Dal.ReadOnlyModel.BarrelModel", b =>
                {
                    b.HasOne("BarrelsAccounting.Accounting.Domain.Barrel", null)
                        .WithOne()
                        .HasForeignKey("BarrelsAccounting.Accounting.Dal.ReadOnlyModel.BarrelModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BarrelsAccounting.Accounting.Dal.ReadOnlyModel.BatchModel", "BatchAttributes", b1 =>
                        {
                            b1.Property<string>("BatchNumber")
                                .HasColumnType("text")
                                .HasColumnName("BatchNumber");

                            b1.Property<string>("AttestationStatus")
                                .HasColumnType("text")
                                .HasColumnName("AttestationStatus");

                            b1.HasKey("BatchNumber");

                            b1.HasIndex("BatchNumber");

                            b1.ToTable("Batch", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BatchNumber")
                                .HasPrincipalKey("Code");
                        });

                    b.OwnsOne("BarrelsAccounting.Accounting.Dal.ReadOnlyModel.CodeModel", "CodeAttributes", b1 =>
                        {
                            b1.Property<string>("MaterialCode")
                                .HasColumnType("text")
                                .HasColumnName("MaterialCode");

                            b1.Property<string>("Gloss")
                                .HasColumnType("text")
                                .HasColumnName("Gloss");

                            b1.Property<string>("Material")
                                .HasColumnType("text")
                                .HasColumnName("Material");

                            b1.Property<string>("MaterialType")
                                .HasColumnType("text")
                                .HasColumnName("MaterialType");

                            b1.Property<string>("ProviderName")
                                .HasColumnType("text")
                                .HasColumnName("ProviderName");

                            b1.HasKey("MaterialCode");

                            b1.HasIndex("MaterialCode");

                            b1.ToTable("Code", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MaterialCode")
                                .HasPrincipalKey("Code");
                        });

                    b.Navigation("BatchAttributes");

                    b.Navigation("CodeAttributes");
                });

            modelBuilder.Entity("BarrelsAccounting.Accounting.Domain.Aggregate", b =>
                {
                    b.HasOne("BarrelsAccounting.Accounting.Domain.ProductionStorage", null)
                        .WithMany("Aggregates")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarrelsAccounting.Accounting.Domain.ProductionStorage", b =>
                {
                    b.Navigation("Aggregates");
                });
#pragma warning restore 612, 618
        }
    }
}
